-- v004: data-driven template category mappings
-- Moves the 49 hardcoded entries from filesystem.rs into a queryable table.

CREATE TABLE IF NOT EXISTS template_category_mappings (
    prefix TEXT PRIMARY KEY,
    category TEXT NOT NULL
);

-- Seed all 49 entries from the original TEMPLATE_CATEGORY_MAPPINGS constant.
INSERT OR IGNORE INTO template_category_mappings (prefix, category) VALUES
    ('Template:Cite', 'cite'),
    ('Module:Citation', 'cite'),
    ('Template:Ref', 'reference'),
    ('Template:Efn', 'reference'),
    ('Module:Reference', 'reference'),
    ('Template:Infobox', 'infobox'),
    ('Module:Infobox', 'infobox'),
    ('Module:InfoboxImage', 'infobox'),
    ('Template:About', 'hatnote'),
    ('Template:See also', 'hatnote'),
    ('Template:Main', 'hatnote'),
    ('Template:Further', 'hatnote'),
    ('Template:Hatnote', 'hatnote'),
    ('Template:Redirect', 'hatnote'),
    ('Template:Distinguish', 'hatnote'),
    ('Module:Hatnote', 'hatnote'),
    ('Template:Navbox', 'navbox'),
    ('Template:Navbar', 'navbox'),
    ('Template:Flatlist', 'navbox'),
    ('Template:Hlist', 'navbox'),
    ('Module:Navbox', 'navbox'),
    ('Module:Navbar', 'navbox'),
    ('Template:Blockquote', 'quotation'),
    ('Template:Cquote', 'quotation'),
    ('Template:Quote', 'quotation'),
    ('Template:Poem', 'quotation'),
    ('Template:Verse', 'quotation'),
    ('Module:Quotation', 'quotation'),
    ('Template:Ambox', 'message'),
    ('Template:Article quality', 'message'),
    ('Template:Stub', 'message'),
    ('Template:Update', 'message'),
    ('Template:Citation needed', 'message'),
    ('Template:Cn', 'message'),
    ('Template:Clarify', 'message'),
    ('Template:When', 'message'),
    ('Template:As of', 'message'),
    ('Module:Message', 'message'),
    ('Template:Sidebar', 'sidebar'),
    ('Template:Portal', 'sidebar'),
    ('Template:Remilia events', 'sidebar'),
    ('Module:Sidebar', 'sidebar'),
    ('Template:Repost', 'repost'),
    ('Template:Mirror', 'repost'),
    ('Template:Goldenlight repost', 'repost'),
    ('Module:Repost', 'repost'),
    ('Template:Etherscan', 'blockchain'),
    ('Template:Explorer', 'blockchain'),
    ('Template:OpenSea', 'blockchain');
